### ISSUE TITLE
Improve JavaScript to support Nashorn and Rhino

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej-ui-swing#46] opened 2015-06-08 17:42 UTC
For Java8 compatibility we need to support Nashorn-based JavaScript. We need to do so in a way that preserves existing Rhino-based scripts.

Since we can't differentiate based on the `.js` extension, a few options would be:

* add `.nashorn.js` extension with JSR-223 Nashorn JS engine.
* parse optional nashorn flag from first line of script and use rhino as default

We also need to decide if there should be two JavaScript entries on the script language menu.

See also: https://github.com/imagej/imagej/issues/105

**Comment by ctrueden** [comment] 2015-06-11 16:38
Duplicate of imagej/imagej#116.

**Closed by ctrueden** 2015-06-11 16:38 UTC
Labels: deployment
